# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# orbs
orbs:
  # github-super-linter: circleci/github-super-linter@1.0.1
  ggshield: gitguardian/ggshield@1.1.4

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  lint:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: cimg/openjdk:19.0.2
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "lint"
          command: "echo Hello, World!"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  # lint-code:
  #   jobs:
  #     - github-super-linter/lint
  scan_my_commits:
    jobs:
      - ggshield/scan:
          name: ggshield-scan
          # base_revision: 
          revision: <<pipeline.git.revision>>
