# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# orbs
orbs:
  # github-super-linter: circleci/github-super-linter@1.0.1
  ggshield: gitguardian/ggshield@1.1.4

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  test-job:
    # test
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: cimg/openjdk:19.0.2
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: run-test
          command: "./test/test.sh component.py"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  # lint-code:
  #   jobs:
  #     - github-super-linter/lint
  default_workflow:
    jobs:
      - ggshield/scan:
          name: ggshield-scan
          # base_revision: 
          revision: <<pipeline.git.revision>>
          context: 
            - demo
      - test-job:
          name: test-1
          requires: 
            - ggshield-scan
      - test-job:
          name: test-2
          requires: 
            - test-1
      - test-job:
          name: test-3
          requires: 
            - test-2
            - ggshield-scan


